Revert "Convert from base::Bind and base::Callback to Once/Repeating in media"
This reverts commit f4723a7ed6c63feae803b7ce0c6053a1daf8a8ea.

Reason for revert: cdm_storage_id.cc:112:45: error: expected ')'
https://ci.chromium.org/p/chrome/builders/ci/chromeos-kevin-chrome/8936

Original change's description:
> Convert from base::Bind and base::Callback to Once/Repeating in media
> 
> This CL converts base::Callback (and corresponding calls to base::Bind)
> to either base::OnceCallback or base::RepeatingCallback in
> chrome/browser/media. In general a base::OnceCallback is preferred since
> that's a stronger API guarantee, so that's been done where safe.
> 
> Bug: 1007635
> Change-Id: Ie3113c61db1ae43ce2e31c262f023d714f42dfc0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2321003
> Commit-Queue: Will Cassella <cassew@google.com>
> Reviewed-by: Frank Liberato <liberato@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#792380}

TBR=liberato@chromium.org,cassew@google.com

Change-Id: Ie1ee4eb9a5a81ef346e38e21fff6535ef29e2790
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: 1007635
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2324498
Reviewed-by: Ben Pastene <bpastene@chromium.org>
Commit-Queue: Ben Pastene <bpastene@chromium.org>
Cr-Commit-Position: refs/heads/master@{#792425}