IWYU: std::vector used in fuzzy_finder.h requires including <vector>
Build with libstdc++ fails with:
In file included from ../../chrome/browser/ui/commander/fuzzy_finder.cc:5:
../../chrome/browser/ui/commander/fuzzy_finder.h:30:23: error: ‘std::vector’ has not been declared
   30 |                  std::vector<gfx::Range>* matched_ranges);
      |                       ^~~~~~

Bug: 957519
Change-Id: Id290b8f93e0f5741d88d6a6e4c75f3c0c0e9f636
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2340038
Reviewed-by: Elly Fong-Jones <ellyjones@chromium.org>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#795906}