Revert "Update Mac memory code references"
This reverts commit 994f22b51a586390c36b5713812baeae1e96262a.

Reason for revert: Probably Tree closer.

https://ci.chromium.org/p/chromium/builders/ci/Cast%20Android%20(dbg)/110678?

Step compile failed. Error logs are shown below:
[76/115] CXX obj/components/services/heap_profiling/public/cpp/cpp/profiling_client.o
FAILED: obj/components/services/heap_profiling/public/cpp/cpp/profiling_client.o
/b/s/w/ir/cache/goma/client/gomacc ../../third_party/llvm-build/Release+Asserts/bin/clang++ -MMD -MF...(too long)
In file included from ../../components/services/heap_profiling/public/cpp/profiling_client.cc:11:
In file included from ../../base/allocator/allocator_interception_mac.h:11:
../../third_party/apple_apsl/malloc.h:27:10: fatal error: 'mach/boolean.h' file not found
#include <mach/boolean.h>
^~~~~~~~~~~~~~~~
1 error generated.



Original change's description:
> Update Mac memory code references
> 
> The Mac malloc interceptor relies on internals of macOS.
> Update those internals and links to the 10.15 versions.
> 
> There is no actual difference in the code that is relied on,
> but the code references were to 10.7 and 10.9.
> 
> Bug: none
> Change-Id: I335007a338c4d3ce4e8297c325ac765a384510f0
> Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2376886
> Commit-Queue: Avi Drissman <avi@chromium.org>
> Commit-Queue: Mark Mentovai <mark@chromium.org>
> Auto-Submit: Avi Drissman <avi@chromium.org>
> Reviewed-by: Mark Mentovai <mark@chromium.org>
> Cr-Commit-Position: refs/heads/master@{#801644}

TBR=avi@chromium.org,mark@chromium.org

Change-Id: Ic868ec40c2622c763b37b4a4d8615e1a25dede60
No-Presubmit: true
No-Tree-Checks: true
No-Try: true
Bug: none
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2377030
Reviewed-by: Hayato Ito <hayato@chromium.org>
Commit-Queue: Hayato Ito <hayato@chromium.org>
Cr-Commit-Position: refs/heads/master@{#801647}