libstdc++: do not pass const types to std::vector in autofill structured address component.
libstdc++ std::vector does not allow const value types:
/usr/include/c++/9/bits/stl_vector.h: In instantiation of ‘class std::vector<const std::__cxx11::basic_string<short unsigned int, base::string16_internals::string16_char_traits> >’:
../../components/autofill/core/browser/data_model/autofill_structured_address_component.cc:436:37:   required from here
/usr/include/c++/9/bits/stl_vector.h:398:66: error: static assertion failed: std::vector must have a non-const, non-volatile value_type

Bug: 957519
Change-Id: I0887c89a185749014a180cca8aec20f646bd16b7
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2317192
Reviewed-by: Parastoo Geranmayeh <parastoog@google.com>
Commit-Queue: José Dapena Paz <jdapena@igalia.com>
Cr-Commit-Position: refs/heads/master@{#791445}