Add missing dep //chrome/browser -> //chrome/common:buildflags
Should fix:
../../chrome/browser/safe_browsing/android/safe_browsing_bridge.cc -o obj/chrome/browser/safe_browsing/android/android/safe_browsing_bridge.o
In file included from ../../chrome/browser/safe_browsing/android/safe_browsing_bridge.cc:7:
../../chrome/browser/profiles/profile_manager.h:28:10: fatal error: 'chrome/common/buildflags.h' file not found

Bug: 1108424
Change-Id: Ib5a8787c60d6e3d8c166dcbcc4dedfecd4a1849c
Fixes: 1108424
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2315498
Reviewed-by: Peter Wen <wnwen@chromium.org>
Commit-Queue: Peter Wen <wnwen@chromium.org>
Auto-Submit: Andrew Grieve <agrieve@chromium.org>
Cr-Commit-Position: refs/heads/master@{#791225}