Make WebRTC a public_dep of //services/network/public/cpp:cpp_base
I think this is just reflecting reality. Consider this build error:

In file included from services/network/public/mojom/network_context.mojom.h:59:
In file included from services/network/public/mojom/p2p.mojom.h:32:
In file included from services/network/public/mojom/p2p.mojom-forward.h:131:
In file included from services/network/public/cpp/p2p_param_traits.h:18:
In file included from services/network/public/cpp/p2p_socket_type.h:17:
third_party/webrtc/rtc_base/async_packet_socket.h:16:10: fatal error: 'rtc_base/constructor_magic.h' file not found
 #include "rtc_base/constructor_magic.h"

network_context.mojom.h ends up including
third_party/webrtc/rtc_base/async_packet_socket.h. But that file, being
part of WebRTC, assumes that it can include headers without a path, i.e.
that its include flags are on the compiler's command line. Thus anyone
who includes network_context.mojom.h has to depend on WebRTC or else
they'll get that compiler error.

WebRTC is a private dep of //services/network/public/cpp:cpp_base and it
looks like it needs to be a public dep.

Change-Id: Idc6497ba64dfc54d2b82bdffbc6e46407f54040f
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2330610
Commit-Queue: Adam Langley <agl@chromium.org>
Reviewed-by: John Abd-El-Malek <jam@chromium.org>
Cr-Commit-Position: refs/heads/master@{#793911}