[ios] Compile Intents.intentdefinition as part of the build
Previously the source file were manually generated by a developer
in a separate blank Xcode project. This make editing the file more
inconvenient (risk of forgetting to copy the generated source file,
need to have a separate project, ...).

Instead, use the new template from build/ios/intent_definition.gni
to integrate the compilation of .intentdefinition as part of the
build with gn/ninja.

The file ios/chrome/app/intents/Intents.intentdefinition had to
be changed to fix compilation errors when using Xcode 11+ to do
the compilation.

The errors fixed are:

  Intents.intentdefinition: error: OpenInChrome.url: Parameter
  voice-only prompt dialog can’t be empty. Alternately, this
  parameter can be marked as unresolvable.

  Intents.intentdefinition: warning: SearchInChrome: The shortcut
  suggestion with ‘(No Parameters)’ parameter combination must
  have a summary.

Bug: none
Change-Id: I8dbbc3a0e5f7ed350c4c81cfaf303f4a065d6731
Reviewed-on: https://chromium-review.googlesource.com/c/chromium/src/+/2283752
Commit-Queue: Sylvain Defresne <sdefresne@chromium.org>
Reviewed-by: Olivier Robin <olivierrobin@chromium.org>
Cr-Commit-Position: refs/heads/master@{#787266}